\input texinfo

@setttitle Guide of SKSNSim

@titlepage

@title Guide of SKSNSim
@page
@vskip 0t plus 1filll
@end titlepage

@contents

@node Top
@top Top


This documents is written for user and developper.

The repository holds library of cross section, flux and kinematics generator.
You can generate kinematics vectors of the SKROOT MC class with selecting the cross section model and flux model.

You can create new flux model and cross section model as a C++ class as following manner.

@node Usage
@chapter Basic

@node For developper
@chapter Implementation guide
@section Cross section model

@section Flux model

@bye
